### ISSUE TITLE
Upgrade Next.js to 10.1 and enable Webpack 5

### ISSUE THREAD

**Issue by urish** [Pull-Request-Community/pull-request-community-website#104]
This should make the project run faster (in dev mode), speed up `npm install` and make `node_modules` smaller.

Background info: https://nextjs.org/blog/next-10-1

How to enable webpack 5: https://nextjs.org/docs/messages/webpack5

In a nutshell: 
1. Update next.js version in package.json
2. Add a few lines to `next.config.js`, as explained [here](https://nextjs.org/docs/messages/webpack5)
3. Check that everything is working

**Comment by EladTal14** [comment]
Hi Uri, I can take this one.

**Comment by EladTal14** [comment]
Hi Uri, I Read the docs about both things and added a next.config.js file and followed the instructions, but I'm getting a warning  that I haven't found a solution for tell me if you know this one.
![warning webpack5](https://user-images.githubusercontent.com/72404439/113268592-37b6f980-92e0-11eb-8252-d90e09019e88.PNG)
@urish

**Comment by urish** [comment]
Hmm there's an open issue about this:

https://github.com/vercel/next.js/issues/23533

Sounds like it's only a warning and it should still work, but you can try asking on that issue if anybody found a solution or a workaround

**Comment by EladTal14** [comment]
Awesome I will. also posted on stackoverflow.

**Comment by domosedov** [comment]
> Hi Uri, I Read the docs about both things and added a next.config.js file and followed the instructions, but I'm getting a warning that I haven't found a solution for tell me if you know this one.
> ![warning webpack5](https://user-images.githubusercontent.com/72404439/113268592-37b6f980-92e0-11eb-8252-d90e09019e88.PNG)
> @urish

`rm -rf node_modules && npm i` help me to fix that

**Comment by EladTal14** [comment]
Tried your solution but the warning still comes up, did you do anything else or found diffrent solution.
@domosedov

**Comment by phibersoft** [comment]
I m getting this warning too.
I deleted package-lock.json and node modules folder and still getting.

Is any different solutions?

![image](https://user-images.githubusercontent.com/54160817/113476946-5f949180-9487-11eb-97c9-14718e66e0d3.png)

**Comment by EladTal14** [comment]
Just talked with the guys in webpack they said they will fix this bug after their holidays. 
He said its just a warning our build will work but persistent caching won't work.
@urish

**Comment by urish** [comment]
Thanks!

**Comment by urish** [comment]
Note: Next.js 10.2 has just been released and should fix the Webpack issue. So let's upgrade to 10.2
