### ISSUE TITLE
Fix Bug - Dark Mode State

### ISSUE THREAD

**Issue by MichalPorag** [Pull-Request-Community/pull-request-community-website#149]
**Steps for reproduction:**

1. Clear the 'theme' key in your Local Storage.
2. Click on the moon icon in the top right corner of your screen.

The moon icon changed to the sun icon; however, the theme didn't change.

**Desired result:** 
After cleaning the key in the Local Storage, show the sun icon and click change to the light theme.

**Comment by casasmartinignacio** [comment]
Hi! I can take this issue. I already fix the bug locally. Please pick me and i will send the pr

**Comment by rinaok** [comment]
@MichalPorag Hey :) Can I take this issue?
