### ISSUE TITLE
Fix members labels

### ISSUE THREAD

**Issue by MichalPorag** [Pull-Request-Community/pull-request-community-website#156]
Remove all labels from "עוז יצחק".
Add "Admin" and "Mentor" labels to "מיכל פורג".
Add "Admin" label to ״שמואל שושתרי״  and to ״הילה פיש״.

![image](https://user-images.githubusercontent.com/47606575/168426061-3c4afb0a-cf52-4956-9e1b-06b8599a64e0.png)

**Comment by anattzlil** [comment]
I would like to take this one :)
