### ISSUE TITLE
Change "npm run dev" To "npm start" And Open Localhost

### ISSUE THREAD

**Issue by MichalPorag** [Pull-Request-Community/pull-request-community-website#157]

**Comment by bargalya** [comment]
@MichalPorag i'd like to take this issue

**Comment by bargalya** [comment]
Hi @MichalPorag  if no one took it, can i take it? thanks

**Comment by MichalPorag** [comment]
@bargalya I'm not closing that because of the bug in windows

**Comment by MichalPorag** [comment]
Hi, this issue is not closed because the change does not work on windows. 
@InbarDanieli  do you want to take it?

**Comment by InbarDanieli** [comment]
I would love to take it (:
