### ISSUE TITLE
Pixel Prefect Layout

### ISSUE THREAD

**Issue by MichalPorag** [Pull-Request-Community/pull-request-community-website#159]
Go over the page and make sure everything is pixel-perfect.
For more details see the Figma project: https://www.figma.com/file/Dxl1kxj1iQt6z9eLIvHWBe/pull-request-website?node-id=0%3A1
![image](https://user-images.githubusercontent.com/47606575/168430181-00de9240-4c64-4a01-9838-c4488be68926.png)

**Comment by Noamili** [comment]
i would like to work on this issue
