### ISSUE TITLE
Add a gap between the social media icons

### ISSUE THREAD

**Issue by rinaok** [Pull-Request-Community/pull-request-community-website#168]
It should be:

```
display: flex;
gap: 48px;
```
![Screen Shot 2022-05-17 at 20 18 59](https://user-images.githubusercontent.com/10883919/168872899-912700b3-c498-4143-a8ee-e760a43bf312.png)

**Comment by MichalPorag** [comment]
It supposed to be: 
gap: 4px;

**Comment by InbarDanieli** [comment]
@MichalPorag  please close this issue
#168
