### ISSUE TITLE
Add issue & pull request template to the project

### ISSUE THREAD

**Issue by OmriBarZik** [Pull-Request-Community/pull-request-community-website#188]
# WHATS THE PROBLEM
Github has [introduced](https://github.blog/changelog/2019-10-28-new-issue-template-configuration-options/) a new API to set templates to PRs and issues. 
I think we should implement this

### refrance 
* [dockly issue tempalte](https://github.com/lirantal/dockly/blob/main/.github/ISSUE_TEMPLATE/bug_report.yaml)
* [dockly PR template](https://github.com/lirantal/dockly/blob/main/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by MichalPorag** [comment]
@OmriBarZik do you want to take it

**Comment by OmriBarZik** [comment]
Closing this issue because @MichalPorag added issues templates
