### ISSUE TITLE
Update husky to version 8

### ISSUE THREAD

**Issue by OmriBarZik** [Pull-Request-Community/pull-request-community-website#191]
# WHATS THE PROBLEM
* husky version 4 doesn't work with npm version 7, we should update our husky version 8 to fix this.

**Comment by InbarDanieli** [comment]
@MichalPorag I would like to take this 🐱

**Comment by MichalPorag** [comment]
@InbarDanieli please take one task at a time

**Comment by MichalPorag** [comment]
@InbarDanieli do you want to take it?

**Comment by InbarDanieli** [comment]
I would love too (:
