### ISSUE TITLE
Remove git add in lint-stage

### ISSUE THREAD

**Issue by OmriBarZik** [Pull-Request-Community/pull-request-community-website#193]
# WHAT THE PROBLEM
We get a warning from git when we run git commit, this I because we do `git add` twice in lint-staged

## SUGGESTION
We should remove the `git add` from the lint-stage config in the package.json, [here](https://github.com/Pull-Request-Community/pull-request-community-website/blob/master/package.json#L38) and [here](https://github.com/Pull-Request-Community/pull-request-community-website/blob/master/package.json#L42)

**Comment by InbarDanieli** [comment]
@MichalPorag I would like to take this 😸
