### ISSUE TITLE
Add .gitattributes to the project

### ISSUE THREAD

**Issue by OmriBarZik** [Pull-Request-Community/pull-request-community-website#210]
# WHATS THE PROBLEM
In this project, we have developers that use Windows, Linux, and Mac.
to have a consistent file ending, we should add a `.gitattributes` file so all our commits will have an `LF` line endings

**Comment by MichalPorag** [comment]
@OmriBarZik do you want to take it?

**Comment by OmriBarZik** [comment]
On it :)
