### ISSUE TITLE
There is no background for the role of Former admin label

### ISSUE THREAD

**Issue by Yedidyar** [Pull-Request-Community/pull-request-community-website#241]
**Expected behavior**
It should have a background

**Screenshots**
![image](https://user-images.githubusercontent.com/42849252/176507029-cafda8d2-cd06-416e-ac08-1840496091bc.png)

**Comment by Yedidyar** [comment]
I think that it could be a good first issue

**Comment by lirantal** [comment]
@Yedidyar looks like you could also style it in the likes of a badge, yes, I agree. I think go for it and open a pull request :-)
