### ISSUE TITLE
Add filtering social networks option

### ISSUE THREAD

**Issue by MichalPorag** [Pull-Request-Community/pull-request-community-website#37]
The mission:
Add  filtering social networks option to the members page.

Link to Figma: https://www.figma.com/file/R4hJBfn1ghnKjTV73j0shr/Pull_Req?node-id=0%3A1

![image](https://user-images.githubusercontent.com/47606575/107359038-dabb7600-6adc-11eb-98b5-fdb76310a01d.png)

**Comment by asharonbaltazar** [comment]
Hello, I'd like to contribute. What behavior are you interested in when selecting a social network? Filter that network out or display those members with the network?

**Comment by MichalPorag** [comment]
מעולה😊 
בבקשה רשום את המשימה על שמך.

ההתנהגות המצופה היא שיוצגו רק המשתמשים שיש להם את הרשתות החברתיות אללו. 
אתה יכול לראות בפיגמה איך זה אמור להראות בכל המצבים, אם יש תהיות נוספות מוזמן לשאול פה

**Comment by asharonbaltazar** [comment]
מה החץ עושה?

**Comment by asharonbaltazar** [comment]
Because this is feature with a lot of moving parts, I thought maybe I should check in with you and make sure I'm doing everything as you planned. Here's my completed styling so far:

![image](https://user-images.githubusercontent.com/58940073/107437428-a3f15a00-6af4-11eb-8a40-fb5f1645e9e3.png)

Either way, I believe for this feature to work smoothly, we should use either Redux or Context. This allows us to bypass passing down props. Would love to hear your thoughts on this.

**Comment by ozizhakGT** [comment]
נראה לי ששימוש ב gobal state management זה קצת overkill לפיצר הזה בייחוד שהדאטה הוא סטטי
context זה רעיון מעניין אם משלבים אותו עם useState/useReducer

בכל אופן יהיה אפשר לדבר על זה היום בסדנא :)

תודה רבה על ההשקעה עד כה !

**Comment by asharonbaltazar** [comment]
אז להמשיך עם זה או לא?

**Comment by ozizhakGT** [comment]
הייתי שמח שנתדיין על זה היום בערב :)

**Comment by asharonbaltazar** [comment]
אין בעיה. נשמע מעניין. אני סך הכל נכנסתי לתמונה אתמול.

אני עכשיו נמצא בארצות הברית. האמת היא ש7 בערב בשבילכם זה זמן מתאים לי. מה אתה אומר?

**Comment by ozizhakGT** [comment]
אנחנו מתחילים ב8 עד 10 ממה שידוע לי..במקרה ולא תוכל להגיע נקבע ביחד וננסה לאפיין את המשימה

**Comment by MichalPorag** [comment]
@asharonbaltazar 
מה המצב?
את החושב שתגיע לזה בקרוב? אם לא אני מבקשת שתעשה unassignees כדי שאנשים אחרים יוכלו לקחת את המשימה

**Comment by asharonbaltazar** [comment]
כן, מצטער. פשוט חיכיתי לתשובה לגבי איך לעשות את זה. אין לי בעיה לעשות unassign.

**Comment by MichalPorag** [comment]
@asharonbaltazar 
פחות חשוב לי שתעשה unassignees.
חשוב לי שתתרום ותקבל תא כל המידע שאתה צריך :)
סליחה שהתפספס. רוצה לפנות אלי בפרטי רגע בפייסבוק ונתאם לשבת על זה ביחד?

**Comment by asharonbaltazar** [comment]
אין לי פייסבוק. אבל יש לי סלאק, טלגרם, ווואצאפ.   האימייל שלי הוא: dipbait@outlook.com.

**Comment by binarica** [comment]
I'd be happy to continue working on this issue.

**Comment by Man-RP** [comment]
היי,
אני יכול לעשות את זה.
