### ISSUE TITLE
Adding CONTRIBUTING.md

### ISSUE THREAD

**Issue by avivnakar** [Pull-Request-Community/pull-request-community-website#67]
This helps might help new developers to know how to start contributing. 
What do you think about this? What should be in there?

**Comment by urish** [comment]
Sounds good. I'd start with some guidelines:

1. ask before you start working on something
2. we have monthly workshops where we work on the website. It's a good opportunity for new people to get to know the project
3. the community is run by volunteers, so while we try to communicate fast, we're sometimes busy with life. It may take us a few days (or in rare occasions more) to get back to you or review your pull request. Pinging us with a reminder after a few days is totally okay (we sometimes forget things, sorry).

Then, I'd explain about the general structure of the project, the frameworks / libraries we use (e.g. Next.js), and where to find their docs.

@MichalPorag @ozizhakGT anything you want to add/change?

**Comment by avivnakar** [comment]
Maybe this is included under the "umbrella" of general structure but I would add a section dedicated for conventions and practices used in this project. I guess that names prefixed with ```I``` are interfaces and a detailed list can help disambiguate
