### ISSUE TITLE
Add videos page

### ISSUE THREAD

**Issue by urish** [Pull-Request-Community/pull-request-community-website#71]
We have some great lectures from community members, such as:

- [How I Helped Add an API to The DOM Specification / Benjamin Gruenbaum](https://youtu.be/wXQSpsC1MSk)
- [Git Bisect & rerere / Noa Barki](https://youtu.be/6zklLJHsBME)
- [git push --force / Noaa Barki](https://youtu.be/UfaCFq6jNlU)
- [Getting into Open Source - Bits from my Personal Story / Benjamin Gruenbaum](https://youtu.be/q-2_EXqktj0)

Let's create a page that gives them the stage they deserve :-)

**Comment by angardia** [comment]
@MichalPorag please assign me

**Comment by MichalPorag** [comment]
@shmuelpro do you want to take it?

**Comment by DavidMarom** [comment]
@MichalPorag please assign me

**Comment by DavidMarom** [comment]
@MichalPorag @urish I started working on it on my fork.
Can you create a branch "71-Add-videos-page" on the original repo? I dont want to merge to master: I want to merge to a branch

**Comment by rinaok** [comment]
@DavidMarom Hi David, we already have an open PR for this, https://github.com/Pull-Request-Community/pull-request-community-website/pull/268.
