### ISSUE TITLE
Support disable javascript browser behavior for the site

### ISSUE THREAD

**Issue by avivnakar** [Pull-Request-Community/pull-request-community-website#85]
Some functionality of this site breaks when the browser does not enable JavaScript.
Since this project is mostly rendered on server side, changing the `כווץ/... קרא עוד` functionality to CSS/HTML based can make this site accessible w/o running JavaScript

for example:

- css manipulated details/summary elements utilizing pseudo elements and the attribute selector ```details[open]{display:inline;}```
- checkbox hack with general sibling selector for conditionally displaying/hiding content

I am not familiar with Next.js maybe there might be better solutions to resolve this kind of issues.

**Comment by MichalPorag** [comment]
@avivnakar 
Hi! thank you :) 
This issue is in low priority, but you are welcome to try solved it, and if it will work good we will check it and merge. 
About a solution in Next.js, I don't know. But, @urish , do you have something to add about it?

**Comment by urish** [comment]
Agreed!

Not aware of something specific to Next.js
